name: "Unit & Smoke Tests - conda"
on:
  pull_request:
    paths:
      - test-example/**
      
  workflow_dispatch:

defaults:
  run:
    shell: bash -el {0}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Copy Repository Contents
        uses: actions/checkout@main   
   
      - name: Install Conda environment
        run: |
          conda env create --name course --file test-example/conda-environment.yaml
        shell: bash

      - name: Activate Conda environment
        run: conda run --name course bash -c 'pip install -U pytest'
      
      - name: Run tests
        run: |
          conda run --name course pytest test-example/
        env:
          WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}